#!/usr/bin/env bash

RED="\033[31;1m"
GREEN="\033[32;1m"
YELLOW="\033[33;1m"
BLUE="\033[34;1m"
PURPLE="\033[35;1m"
CYAN="\033[36;1m"
PLAIN="\033[0m"

if [ "$EUID" -ne 0 ]; then
  echo -e "[${RED}●${PLAIN}] Script needs to be run as root" && exit
fi

if readlink /proc/$$/exe | grep -qs "dash"; then
  echo -e "[${RED}●${PLAIN}] Script needs to be run with bash" && exit
fi

echo -e "${CYAN}----------------------------------------------------------------${PLAIN}"
echo -e "${PURPLE}'||'  '|' '||''|.   .|'''.|${PLAIN}  ${BLUE}+-+ +-+ +-+ +-+ +-+ +-+ +-+ +-+ +-+${PLAIN}"
echo -e "${PURPLE} '|.  .'   ||   ||  ||..  '${PLAIN}  ${BLUE}|C| |Y| |B| |E| |R| |T| |I| |Z| |E|${PLAIN}"
echo -e "${PURPLE}  ||  |    ||...|'   ''|||.${PLAIN}  ${BLUE}+-+ +-+ +-+ +-+ +-+ +-+ +-+ +-+ +-+${PLAIN}"
echo -e "${PURPLE}   |||     ||      .    '||${PLAIN}  ${GREEN}Created by Doctype${PLAIN}"
echo -e "${PURPLE}    |     .||.      |'...|'${PLAIN}  ${GREEN}Copyright 2021 Cybertize,${PLAIN}"
echo -e "${PURPLE}      Linux Debian-10      ${PLAIN}  ${GREEN}Allright Reserved.${PLAIN}"
echo -e "${CYAN}----------------------------------------------------------------${PLAIN}"
echo -e "${BLUE}CYBERTIZE PLUGIN MAIN MENU${PLAIN}"
echo -e "${CYAN}02${PLAIN}) ${GREEN}create${PLAIN}     - ${YELLOW}Buat akaun pengguna untuk dropbear & openvpn${PLAIN}"
echo -e "${CYAN}03${PLAIN}) ${GREEN}active${PLAIN}     - ${YELLOW}Tukar tempoh tarikh luput akaun pengguna${PLAIN}"
echo -e "${CYAN}04${PLAIN}) ${GREEN}password${PLAIN}   - ${YELLOW}Tukar kata laluan akaun pengguna${PLAIN}"
echo -e "${CYAN}05${PLAIN}) ${GREEN}login${PLAIN}      - ${YELLOW}Senaraikan pengguna yang log masuk${PLAIN}"
echo -e "${CYAN}06${PLAIN}) ${GREEN}lists${PLAIN}      - ${YELLOW}Senaraikan semua akaun pengguna${PLAIN}"
echo -e "${CYAN}07${PLAIN}) ${GREEN}lock${PLAIN}       - ${YELLOW}Kunci atau nyahdayakan akaun pengguna${PLAIN}"
echo -e "${CYAN}08${PLAIN}) ${GREEN}unlock${PLAIN}     - ${YELLOW}Buka kunci atau dayakan akaun pengguna${PLAIN}"
echo -e "${CYAN}09${PLAIN}) ${GREEN}delete${PLAIN}     - ${YELLOW}Padamkan akaun pengguna${PLAIN}"
echo -e "${CYAN}09${PLAIN}) ${GREEN}speedtest${PLAIN}  - ${YELLOW}Server speedtest${PLAIN}"
echo -e "${CYAN}09${PLAIN}) ${GREEN}detail${PLAIN}     - ${YELLOW}Rinkasan maklumat server${PLAIN}"
echo ""
read -p "Sila pilih salah satu menu yang tersenarai " MENUCHOICE

while true ; do
  case $MENUCHOICE in
    01|create )
      bash /usr/local/bin/create
      break
    ;;
    02|active )
      bash /usr/local/bin/active
      break
    ;;
    03|password )
      bash /usr/local/bin/password
      break
    ;;
    04|login )
      bash /usr/local/bin/login
      break
    ;;
    05|lists )
      bash /usr/local/bin/lists
      break
    ;;
    06|lock )
      bash /usr/local/bin/lock
      break
    ;;
    07|unlock )
      bash /usr/local/bin/unlock
      break
    ;;
    08|delete )
      bash /usr/local/bin/delete
      break
    ;;
    09|speedtest )
      bash /usr/local/bin/speedtest
      break
    ;;
    10|detail )
      bash /usr/local/bin/detail
      break
    ;;
    * )
      echo -e "[${RED}●${PLAIN}] Pilihan yang anda masukkan tidak sah!"
      exit 0
    ;;
  esac
done
