#!/bin/bash

read -p "[PASSWORD] Masukkan nama pengguna: " NAMAPENGGUNA
egrep "^$NAMAPENGGUNA" /etc/passwd >/dev/null
if [ $? -ne 0 ]; then
    echo "Nama pengguna tidak dijumpai!"
    exit 1
fi
read -p "Input new PASSWORD for user $NAMAPENGGUNA: " password
egrep "^$NAMAPENGGUNA" /etc/passwd >/dev/null
echo -e "$password\n$password" | passwd $NAMAPENGGUNA
echo "======================================"
echo "Berjaya ganti kata laluan pengguna."
echo "======================================"