#!/bin/bash

read -p "[UNLOCK] Masukkan nama pengguna: " NAMAPENGGUNA
egrep "^$NAMAPENGGUNA" /etc/passwd >/dev/null
if [ $? -ne 0 ]; then
  echo "Nama pengguna tidak ditemukan!"
  exit 1
fi
passwd -u $NAMAPENGGUNA
echo "======================================"
echo "Berjaya buka kunci akaun pengguna."
echo "======================================"
